spring:
  cloud:
    gateway:
      routes:
        - id: route1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            Path= /api/customers/**
            
        - id: route2
          uri: lb://INVENTORY-SERVICE
          predicates:
            Path= /api/products/**
            