spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: route1
          uri: http://localhost:8081
          predicates:
            - Path= /api/customers/**
            
        - id: route2
          uri: http://localhost:8082
          predicates:
            - Path= /api/products/**
            